"""make_operation_id_nullable

Revision ID: d74ee7ac2e29
Revises: 759764205143
Create Date: 2026-04-21 19:38:24.452731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74ee7ac2e29'
down_revision: Union[str, None] = '759764205143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'operation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'operation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
